
const KEY="family-cfo-v3";
const oldKey="family-cfo-v2";
const baseSeed={budget:105,expenses:[],receipts:[],products:[],lastStore:"Eurospin",shopping:[
{id:1,name:"Latte",store:"Eurospin",day:1,price:4,done:false},{id:2,name:"Frutta di stagione",store:"Eurospin",day:1,price:10,done:false},{id:3,name:"Yogurt",store:"Eurospin",day:1,price:3,done:false},{id:4,name:"Pollo fresco",store:"Eurospin",day:1,price:9,done:false},{id:5,name:"Verdure",store:"Eurospin",day:1,price:10,done:false},{id:6,name:"Pesce",store:"Famila",day:2,price:12,done:false},{id:7,name:"Verdure fresche",store:"Famila",day:2,price:7,done:false},{id:8,name:"Pane",store:"Famila",day:2,price:3,done:false}],
pantry:[{id:11,name:"Pasta",pct:60,type:"normal",icon:"🍝"},{id:12,name:"Riso",pct:30,type:"normal",icon:"🍚"},{id:13,name:"Ceci",pct:55,type:"normal",icon:"🫘"},{id:14,name:"Uova",pct:45,type:"normal",icon:"🥚"},{id:15,name:"Patate",pct:35,type:"normal",icon:"🥔"},{id:16,name:"Olio EVO",pct:70,type:"staple",icon:"🫒"},{id:17,name:"Sale",pct:80,type:"staple",icon:"🧂"},{id:18,name:"Zucchero",pct:50,type:"staple",icon:"◻️"}],
selectedDay:"Lun",menu:{Lun:{lunch:"Pasta al pomodoro e verdure",dinner:"Branzino, patate e carote",tags:["pesce","verdure"]},Mar:{lunch:"Riso con zucchine",dinner:"Frittata, pane e insalata",tags:["uova","verdure"]},Mer:{lunch:"Pasta e ceci",dinner:"Pollo fresco con patate",tags:["legumi","carne bianca"]},Gio:{lunch:"Pasta con ricotta e zucchine",dinner:"Minestrone, ceci e pane",tags:["legumi","verdure"]},Ven:{lunch:"Riso con verdure",dinner:"Pesce con contorno",tags:["pesce","verdure"]},Sab:{lunch:"Pasta e ortaggi",dinner:"Carne bianca e verdure",tags:["carne bianca","verdure"]},Dom:{lunch:"Pranzo libero pianificato",dinner:"Legumi, pane e verdure",tags:["legumi","verdure"]}}};
let state;
try{
 const saved=localStorage.getItem(KEY);
 if(saved) state=JSON.parse(saved);
 else {
   const old=localStorage.getItem(oldKey);
   state=old?Object.assign(JSON.parse(JSON.stringify(baseSeed)),JSON.parse(old)):JSON.parse(JSON.stringify(baseSeed));
 }
}catch(e){state=JSON.parse(JSON.stringify(baseSeed));}
if(!Array.isArray(state.products))state.products=[];
if(!Array.isArray(state.receipts))state.receipts=[];
if(!state.lastStore)state.lastStore="Eurospin";
let shopFilter="all", currentReceiptUrl="", currentReceiptText="", parsedReceiptLines=[], linkingProductId=null, barcodeCandidate=null;
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
function eur(n){return new Intl.NumberFormat("it-IT",{style:"currency",currency:"EUR"}).format(Number(n)||0);}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render();}
function toast(t){const el=$("#toast");el.textContent=t;el.style.display="block";clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.style.display="none",1500);}
function foodSpent(){return state.expenses.filter(x=>x.category==="Alimentari").reduce((a,b)=>a+b.amount,0);}
function planned(){return state.shopping.filter(x=>!x.done).reduce((a,b)=>a+(+b.price||0),0);}
function normalize(s){return String(s||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g," ").trim();}
function titleCase(s){return String(s||"").toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());}
function uid(prefix){return (prefix||"id")+"-"+Date.now()+"-"+Math.random().toString(36).slice(2,7);}
function openModal(name){$("#"+name+"Modal").classList.add("open");}
function switchScreen(id){$$(".screen").forEach(v=>v.classList.toggle("active",v.id===id));$$(".bottom-nav button").forEach(b=>b.classList.toggle("active",b.dataset.screen===id));window.scrollTo({top:0,behavior:"smooth"});}
$$("[data-screen]").forEach(b=>b.addEventListener("click",()=>switchScreen(b.dataset.screen)));
$$("[data-open]").forEach(b=>b.addEventListener("click",()=>openModal(b.dataset.open)));
$$(".modal-close").forEach(b=>b.addEventListener("click",()=>b.closest(".modal").classList.remove("open")));
$$(".modal").forEach(m=>m.addEventListener("click",e=>{if(e.target===m)m.classList.remove("open");}));
function activateChoice(b){const row=b.closest(".choice-row"),target=b.dataset.target;if(row)row.querySelectorAll(".choice").forEach(x=>x.classList.toggle("active",x===b));const input=$("#"+target);if(input)input.value=b.dataset.value;}
$$(".choice").forEach(b=>b.addEventListener("click",()=>activateChoice(b)));
function selectChoice(target,value){const btn=$('[data-target="'+target+'"][data-value="'+String(value)+'"]');if(btn)activateChoice(btn);}
function levelMeta(p){if(p===0)return["Da comprare","danger"];if(p<=30)return["Poco","warn"];if(p<=60)return["Metà",""];return["OK",""];}
function quickLevel(p){if(p===0)return 0;if(p<=30)return 25;if(p<=70)return 50;return 100;}
function tripHtml(code,title,arr){const total=arr.reduce((a,b)=>a+(+b.price||0),0);let names=arr.slice(0,3).map(x=>x.name).join(" · ");if(arr.length>3)names+=" · …";if(!names)names="Nessun articolo";return '<div class="trip"><div class="trip-logo">'+code+'</div><div class="trip-main"><strong>'+title+'</strong><span>'+names+'</span></div><div class="trip-price"><b>'+eur(total)+'</b><span>'+arr.length+' prodotti</span></div></div>';}
function renderHome(){const spent=foodSpent(),rem=state.budget-spent,pct=Math.max(0,Math.min(100,Math.round(spent/state.budget*100)));$("#remaining").textContent=eur(Math.max(0,rem));$("#spent").textContent=eur(spent);$("#planned").textContent=eur(planned());$("#ringPct").textContent=pct+"%";$("#ring").style.setProperty("--deg",(pct*3.6)+"deg");$("#budgetCopy").textContent=spent===0?"Tutto il budget è ancora disponibile":rem>=0?eur(rem)+" ancora disponibili":"Budget superato di "+eur(Math.abs(rem));const low=state.pantry.filter(x=>x.pct<=30);$("#lowHero").textContent=low.length;$("#pantryMetric").textContent=state.pantry.length;$("#shoppingMetric").textContent=state.shopping.filter(x=>!x.done).length;$("#lowMetric").textContent=low.length;const d1=state.shopping.filter(x=>x.day===1&&!x.done),d2=state.shopping.filter(x=>x.day===2&&!x.done);$("#tripCards").innerHTML=tripHtml("EU","Spesa 1 · Eurospin",d1)+tripHtml("FA","Spesa 2 · Famila",d2);const buy=state.pantry.filter(x=>x.pct===0).map(x=>x.name),lows=state.pantry.filter(x=>x.pct>0&&x.pct<=30).map(x=>x.name);$("#insightText").textContent=buy.length?"Da comprare: "+buy.join(", ")+". Le scorte base entrano in lista solo quando finiscono.":lows.length?"Stanno finendo: "+lows.join(", ")+". Aggiorna il residuo con un tap.":"La dispensa è coperta: evita doppioni e compra solo ciò che manca.";}
function productStats(p){const h=p.prices||[];if(!h.length)return{last:null,min:null,avg:null};const vals=h.map(x=>+x.price).filter(Number.isFinite);return{last:vals[vals.length-1],min:Math.min(...vals),avg:vals.reduce((a,b)=>a+b,0)/vals.length};}
function renderProducts(){const products=state.products.slice().sort((a,b)=>((b.prices||[]).length-(a.prices||[]).length));$("#priceHighlights").innerHTML=products.length?'<div class="price-highlight"><span>📈</span><div><strong>'+products.length+' prodotti monitorati</strong><p>Ogni nuovo scontrino aggiorna automaticamente lo storico prezzi.</p></div></div>':'<div class="price-highlight"><span>🧾</span><div><strong>Lo storico nascerà dagli scontrini</strong><p>Fotografa una spesa: ogni riga diventa un prodotto monitorato.</p></div></div>';$("#productList").innerHTML=products.length?products.map(p=>{const st=productStats(p);return '<button class="product-card" data-product="'+p.id+'"><div class="product-img">'+(p.image?'<img src="'+p.image+'" alt="">':"◫")+'</div><div class="product-main"><strong>'+p.name+'</strong><small>'+(p.brand||"")+(p.quantity?" · "+p.quantity:"")+(p.barcode?" · "+p.barcode:"")+'</small></div><div class="product-price"><b>'+(st.last!=null?eur(st.last):"—")+'</b><small>'+(p.prices||[]).length+' rilevazioni</small></div></button>';}).join(""):'<div class="empty">Nessun prodotto monitorato ancora.</div>';$$("[data-product]").forEach(b=>b.addEventListener("click",()=>openProduct(b.dataset.product)));}
function renderShopping(){const spent=foodSpent(),rem=state.budget-spent;$("#miniSpent").textContent=eur(spent)+" su "+eur(state.budget);$("#miniRemaining").textContent=eur(Math.max(0,rem));const arr=state.shopping.filter(x=>shopFilter==="all"||x.day===+shopFilter);$("#shoppingList").innerHTML=arr.length?arr.map(x=>'<div class="list-item '+(x.done?"done":"")+'" data-shop="'+x.id+'"><button class="check">'+(x.done?"✓":"")+'</button><div class="list-main"><strong>'+x.name+'<span class="store">'+x.store+'</span></strong><small>Spesa '+x.day+'</small></div><div class="price">'+(x.price?eur(x.price):"—")+'</div></div>').join(""):'<div class="empty">Nessun prodotto in questa lista.</div>';$$("[data-shop]").forEach(el=>el.querySelector(".check").addEventListener("click",()=>{const x=state.shopping.find(i=>i.id===+el.dataset.shop);if(x){x.done=!x.done;save();}}));$("#expenseList").innerHTML=state.expenses.length?state.expenses.slice().reverse().map(x=>'<div class="list-item"><div class="food">'+(x.receipt?"🧾":"€")+'</div><div class="list-main"><strong>'+x.store+'</strong><small>'+x.category+(x.note?" · "+x.note:"")+'</small></div><div class="price">'+eur(x.amount)+'</div></div>').join(""):'<div class="empty">Nessuna spesa registrata.</div>';renderProducts();}
$$("#shopTabs button").forEach(b=>b.addEventListener("click",()=>{shopFilter=b.dataset.filter;$$("#shopTabs button").forEach(x=>x.classList.toggle("active",x===b));renderShopping();}));
function renderPantry(){$("#pantryGrid").innerHTML=state.pantry.map(x=>{const m=levelMeta(x.pct),active=quickLevel(x.pct);return '<article class="pantry-card"><div class="pantry-top"><div class="food">'+x.icon+'</div><span class="badge '+m[1]+'">'+(x.type==="staple"?"scorta base":m[0])+'</span></div><h3>'+x.name+'</h3><small>'+(x.type==="staple"?"Solo quando serve · ":"")+m[0]+'</small><div class="bar" style="--pct:'+x.pct+'%"><span></span></div><div class="level-row"><span>'+x.pct+'% stimato</span><span>1 tap</span></div><div class="pantry-levels" data-pan-id="'+x.id+'"><button class="pantry-level '+(active===100?"active":"")+'" data-pct="100">Pieno</button><button class="pantry-level '+(active===50?"active":"")+'" data-pct="50">Metà</button><button class="pantry-level '+(active===25?"active":"")+'" data-pct="25">Poco</button><button class="pantry-level '+(active===0?"active":"")+'" data-pct="0">Finito</button></div></article>';}).join("");$$(".pantry-levels").forEach(row=>row.querySelectorAll(".pantry-level").forEach(btn=>btn.addEventListener("click",()=>{const x=state.pantry.find(i=>i.id===+row.dataset.panId);if(x){x.pct=+btn.dataset.pct;save();toast(x.name+": "+btn.textContent);}})));}
const days=[["Lun","21"],["Mar","22"],["Mer","23"],["Gio","24"],["Ven","25"],["Sab","26"],["Dom","27"]];
function renderMenu(){$("#days").innerHTML=days.map(d=>'<button class="day '+(state.selectedDay===d[0]?"active":"")+'" data-day="'+d[0]+'"><b>'+d[0]+'</b><span>'+d[1]+'</span></button>').join("");$$("[data-day]").forEach(b=>b.addEventListener("click",()=>{state.selectedDay=b.dataset.day;save();}));const m=state.menu[state.selectedDay],tags=m.tags.map(t=>"<span>"+t+"</span>").join("");$("#mealCards").innerHTML='<article class="meal"><div class="meal-head"><span>Pranzo</span><span>12:30</span></div><h3>'+m.lunch+'</h3><p>Usa prima ciò che è già disponibile in casa.</p><div class="tags">'+tags+'</div></article><article class="meal"><div class="meal-head"><span>Cena</span><span>19:30</span></div><h3>'+m.dinner+'</h3><p>Preparazione semplice, con adattamento di consistenza e sale per i bambini.</p><div class="tags">'+tags+'</div></article>';}
function makeReview(){const spent=foodSpent(),rem=state.budget-spent;const pantry=state.pantry.map(x=>"- "+x.name+": "+x.pct+"%"+(x.type==="staple"?" [SCORTA BASE]":"")).join("\n");const buy=state.pantry.filter(x=>x.pct===0).map(x=>"- "+x.name).join("\n")||"- nessuna";const plannedList=state.shopping.filter(x=>!x.done).map(x=>"- Spesa "+x.day+" · "+x.store+": "+x.name+(x.price?" · "+eur(x.price):"")).join("\n")||"- nessun articolo";const prices=state.products.filter(x=>(x.prices||[]).length).slice(0,20).map(x=>{const st=productStats(x);return "- "+x.name+": ultimo "+eur(st.last)+", media "+eur(st.avg)+", minimo "+eur(st.min);}).join("\n")||"- nessuno";return "FAMILY CFO — REVIEW SETTIMANALE\n\nFamiglia: 2 adulti + 2 bambini\nBudget alimentare: "+eur(state.budget)+"\nSpeso alimentari: "+eur(spent)+"\nResiduo budget: "+eur(rem)+"\n\nDISPENSA\n"+pantry+"\n\nDA COMPRARE\n"+buy+"\n\nLISTA PIANIFICATA\n"+plannedList+"\n\nSTORICO PREZZI\n"+prices+"\n\nOBIETTIVO PER CHATGPT\nAnalizza la settimana, evita doppioni, usa prima la dispensa, segnala aumenti o offerte reali rispetto allo storico prezzi e proponi massimo due spese tra Famila ed Eurospin. Le scorte base si comprano solo quando segnate Da comprare.";}
function renderReview(){const spent=foodSpent(),ratio=spent/state.budget,score=Math.max(55,Math.round(96-Math.max(0,ratio-.75)*60-state.pantry.filter(x=>x.pct===0).length*2));$("#score").textContent=score;$("#scoreTitle").textContent=score>=90?"Settimana ben impostata":score>=75?"Buon controllo, qualche aggiustamento":"Rivediamo lista e budget";const notes=[spent<=state.budget?"Sei dentro il budget: "+eur(Math.max(0,state.budget-spent))+" ancora disponibili.":"Hai superato il budget di "+eur(spent-state.budget)+"."];const low=state.pantry.filter(x=>x.pct<=30).map(x=>x.name);if(low.length)notes.push("Da controllare: "+low.join(", ")+".");notes.push(state.products.length?state.products.length+" prodotti hanno già uno storico prezzi.":"Lo storico prezzi inizierà dal primo scontrino analizzato.");$("#reviewNotes").innerHTML=notes.map(n=>'<div class="review-note">'+n+"</div>").join("");$("#reviewText").textContent=makeReview();}
function render(){renderHome();renderShopping();renderPantry();renderMenu();renderReview();}
function findProductByAlias(raw){const n=normalize(raw);let best=null,bestScore=0;for(const p of state.products){for(const a of (p.aliases||[]).concat([p.name||""])){const an=normalize(a);if(an===n)return p;const ta=new Set(an.split(" ").filter(x=>x.length>2)),tb=new Set(n.split(" ").filter(x=>x.length>2));const common=[...ta].filter(x=>tb.has(x)).length,score=common/Math.max(1,Math.max(ta.size,tb.size));if(score>bestScore){bestScore=score;best=p;}}}return bestScore>=.75?best:null;}
function parseMoney(v){return Number(String(v).replace(/\./g,"").replace(",",".").replace(/[^\d.]/g,""))||0;}
function detectStore(text){const n=normalize(text);if(n.includes("eurospin"))return"Eurospin";if(n.includes("famila"))return"Famila";return state.lastStore||"Altro";}
function parseReceipt(text){const rawLines=String(text||"").split(/\n+/).map(x=>x.replace(/\s+/g," ").trim()).filter(Boolean);let total=0;for(const l of rawLines){if(/totale|tot\.|importo/i.test(l)){const ms=l.match(/(\d{1,4}[,.]\d{2})(?!.*\d)/);if(ms)total=parseMoney(ms[1]);}}const skip=/totale|subtot|iva|carta|contanti|resto|bancomat|pagamento|operatore|cassa|scontrino|documento commerciale|lotteria|euro\b|codice fiscale/i;const out=[];for(let i=0;i<rawLines.length;i++){const l=rawLines[i];if(skip.test(l))continue;let m=l.match(/^(.*?)(\d{1,4}[,.]\d{2})\s*[A-Z]?\s*$/);if(!m)continue;let name=m[1].replace(/[\*\-=:]+$/,"").trim();let price=parseMoney(m[2]);if(!name||name.length<3||price<=0)continue;let qty=1,weightKg=null,unitPrice=null;const wm=name.match(/(.*?)(\d+[,.]\d{2,3})\s*(?:kg)?\s*[xX]\s*(\d+[,.]\d{2})\s*$/);if(wm){name=wm[1].trim();weightKg=parseMoney(wm[2]);unitPrice=parseMoney(wm[3]);}else{const qm=name.match(/^(\d+)\s*[xX]\s+(.*)$/);if(qm){qty=+qm[1]||1;name=qm[2].trim();}}name=name.replace(/^\d{4,}\s+/,"").replace(/\s+[A-Z]$/,"").trim();if(name.length<3)continue;const product=findProductByAlias(name);out.push({id:uid("line"),rawName:name,name:product?product.name:titleCase(name),price,qty,weightKg,unitPrice,productId:product?product.id:null});}if(!total&&out.length)total=out.reduce((a,b)=>a+b.price,0);return{store:detectStore(text),total,lines:out.slice(0,80)};}
function renderReceiptLines(){const el=$("#receiptLines");el.innerHTML=parsedReceiptLines.length?parsedReceiptLines.map((x,idx)=>'<div class="receipt-line" data-line="'+x.id+'"><div class="receipt-line-top"><input class="line-name" value="'+String(x.name).replace(/"/g,"&quot;")+'"><input class="line-price" type="number" step=".01" inputmode="decimal" value="'+x.price.toFixed(2)+'"><button class="line-remove" type="button">×</button></div><div class="receipt-line-status '+(x.productId?"known":"")+'">'+(x.productId?"✓ Prodotto già riconosciuto":"Nuovo prodotto · verrà creato nello storico")+'</div></div>').join(""):'<div class="empty">Non ho riconosciuto righe prodotto. Puoi aggiungerle con “+ Riga”.</div>';$$(".receipt-line").forEach(row=>{const line=parsedReceiptLines.find(x=>x.id===row.dataset.line);row.querySelector(".line-name").addEventListener("input",e=>{line.name=e.target.value;const p=findProductByAlias(line.name);line.productId=p?p.id:null;});row.querySelector(".line-price").addEventListener("input",e=>line.price=+e.target.value||0);row.querySelector(".line-remove").addEventListener("click",()=>{parsedReceiptLines=parsedReceiptLines.filter(x=>x.id!==line.id);renderReceiptLines();});});}
async function analyzeReceipt(file){$("#receiptStatusText").textContent="Sto leggendo prodotti e prezzi…";$("#ocrProgress").hidden=false;$("#receiptDetected").hidden=true;$("#ocrBar").style.width="4%";currentReceiptText="";try{if(!window.Tesseract)throw new Error("OCR non caricato");const res=await Tesseract.recognize(file,"ita",{logger:m=>{if(m.status==="recognizing text"&&m.progress!=null)$("#ocrBar").style.width=Math.round(m.progress*100)+"%";}});currentReceiptText=res.data.text||"";const parsed=parseReceipt(currentReceiptText);parsedReceiptLines=parsed.lines;selectChoice("receiptStoreValue",parsed.store);$("#receiptTotal").value=parsed.total?parsed.total.toFixed(2):"";renderReceiptLines();$("#ocrBar").style.width="100%";$("#receiptStatusText").textContent=parsed.lines.length?"Ho trovato "+parsed.lines.length+" righe. Controlla solo eventuali dubbi.":"OCR completato: aggiungi le righe non lette.";$("#receiptDetected").hidden=false;}catch(err){$("#receiptStatusText").textContent="Lettura automatica non disponibile. Puoi inserire totale e righe qui sotto.";parsedReceiptLines=[];renderReceiptLines();$("#receiptDetected").hidden=false;$("#ocrProgress").hidden=true;}}
function openReceiptCamera(){$("#receiptInput").click();}
$("#receiptHomeBtn").addEventListener("click",openReceiptCamera);$("#receiptShoppingBtn").addEventListener("click",openReceiptCamera);
$("#receiptInput").addEventListener("change",e=>{const f=e.target.files&&e.target.files[0];if(!f)return;if(currentReceiptUrl)URL.revokeObjectURL(currentReceiptUrl);currentReceiptUrl=URL.createObjectURL(f);$("#receiptThumb").innerHTML='<img src="'+currentReceiptUrl+'" alt="Foto scontrino">';$("#receiptThumb").style.display="block";$("#receiptModal").classList.add("open");analyzeReceipt(f);});
$("#addReceiptLine").addEventListener("click",()=>{parsedReceiptLines.push({id:uid("line"),rawName:"",name:"",price:0,qty:1,weightKg:null,unitPrice:null,productId:null});renderReceiptLines();});
function ensureProduct(line){let p=line.productId?state.products.find(x=>x.id===line.productId):findProductByAlias(line.name);if(!p){p={id:uid("p"),barcode:null,name:line.name||titleCase(line.rawName),brand:"",quantity:"",image:"",aliases:[],prices:[]};state.products.push(p);}if(!p.aliases)p.aliases=[];if(line.rawName&&!p.aliases.some(a=>normalize(a)===normalize(line.rawName)))p.aliases.push(line.rawName);return p;}
$("#confirmReceiptBtn").addEventListener("click",()=>{const total=+$("#receiptTotal").value||parsedReceiptLines.reduce((a,b)=>a+(+b.price||0),0);if(total<=0){toast("Controlla il totale");return;}const store=$("#receiptStoreValue").value,receiptId=uid("r"),date=new Date().toISOString();state.expenses.push({id:receiptId,amount:total,store,category:"Alimentari",note:"Scontrino analizzato",receipt:true});const savedLines=[];for(const line of parsedReceiptLines.filter(x=>x.name&&x.price>0)){const p=ensureProduct(line);if(!p.prices)p.prices=[];let unit=line.price;if(line.weightKg)unit=line.price/line.weightKg;else if(line.qty>1)unit=line.price/line.qty;p.prices.push({date,store,price:+line.price,qty:line.qty||1,weightKg:line.weightKg||null,unitPrice:unit,receiptId});savedLines.push({name:line.name,price:+line.price,productId:p.id});}state.receipts.push({id:receiptId,date,store,total,lines:savedLines,rawText:currentReceiptText});state.lastStore=store;$("#receiptModal").classList.remove("open");$("#receiptInput").value="";save();switchScreen("shopping");toast("Scontrino e prezzi salvati");});
function openProduct(id){const p=state.products.find(x=>x.id===id);if(!p)return;const h=(p.prices||[]).slice(),st=productStats(p),max=Math.max(...h.map(x=>x.price),1);$("#productDetail").innerHTML='<div class="product-detail-head"><div class="product-img">'+(p.image?'<img src="'+p.image+'" alt="">':"◫")+'</div><div><h2>'+p.name+'</h2><p>'+([p.brand,p.quantity,p.barcode].filter(Boolean).join(" · ")||"Prodotto locale")+'</p></div></div><div class="price-kpis"><article><span>Ultimo</span><b>'+(st.last!=null?eur(st.last):"—")+'</b></article><article><span>Media</span><b>'+(st.avg!=null?eur(st.avg):"—")+'</b></article><article><span>Minimo</span><b>'+(st.min!=null?eur(st.min):"—")+'</b></article></div>'+(h.length?'<div class="history-chart">'+h.slice(-12).map(x=>'<div class="history-bar" style="height:'+Math.max(8,Math.round(x.price/max*94))+'px" title="'+eur(x.price)+'"></div>').join("")+'</div><div class="history-list">'+h.slice().reverse().slice(0,12).map(x=>'<div class="history-row"><span>'+new Date(x.date).toLocaleDateString("it-IT")+' · '+x.store+'</span><b>'+eur(x.price)+'</b></div>').join("")+'</div>':'<div class="empty">Nessun prezzo registrato.</div>')+'<div class="action-row"><button class="secondary" id="linkBarcodeBtn">Abbina barcode</button></div>';$("#productModal").classList.add("open");$("#linkBarcodeBtn").addEventListener("click",()=>{linkingProductId=p.id;$("#productModal").classList.remove("open");openBarcode();});}
function openBarcode(){barcodeCandidate=null;$("#barcodeInput").value="";$("#barcodeResult").innerHTML='<div class="empty">Scatta il barcode o inserisci EAN/GTIN.</div>';$("#barcodeModal").classList.add("open");}
$("#barcodeOpenBtn").addEventListener("click",()=>{linkingProductId=null;openBarcode();});
$("#barcodeCameraBtn").addEventListener("click",()=>$("#barcodeImageInput").click());
$("#barcodeImageInput").addEventListener("change",async e=>{const f=e.target.files&&e.target.files[0];if(!f)return;if(!("BarcodeDetector" in window)){toast("Su questo browser inserisci il codice manualmente");return;}try{const img=await createImageBitmap(f);const formats=(await BarcodeDetector.getSupportedFormats()).filter(x=>["ean_13","ean_8","upc_a","upc_e","code_128"].includes(x));const detector=new BarcodeDetector({formats:formats.length?formats:undefined});const found=await detector.detect(img);if(!found.length){toast("Barcode non trovato");return;}$("#barcodeInput").value=found[0].rawValue;lookupBarcode(found[0].rawValue);}catch(e2){toast("Inserisci il codice manualmente");}});
$("#barcodeLookupBtn").addEventListener("click",()=>lookupBarcode($("#barcodeInput").value.trim()));
async function lookupBarcode(code){if(!/^\d{8,14}$/.test(code)){toast("EAN/GTIN non valido");return;}$("#barcodeResult").innerHTML='<div class="empty">Cerco il prodotto…</div>';try{const url="https://world.openfoodfacts.org/api/v3/product/"+encodeURIComponent(code)+"?fields=code,product_name,abbreviated_product_name,brands,quantity,image_front_small_url,product_quantity,product_quantity_unit&lc=it&cc=it";const r=await fetch(url);if(!r.ok)throw new Error("not found");const data=await r.json(),p=data.product;if(!p)throw new Error("not found");barcodeCandidate={barcode:code,name:p.product_name||p.abbreviated_product_name||("Prodotto "+code),brand:p.brands||"",quantity:p.quantity||"",image:p.image_front_small_url||""};renderBarcodeResult();}catch(e){barcodeCandidate={barcode:code,name:"Prodotto "+code,brand:"",quantity:"",image:""};renderBarcodeResult(true);}}
function renderBarcodeResult(localOnly){const p=barcodeCandidate;$("#barcodeResult").innerHTML='<div class="barcode-result"><div class="barcode-result-row"><div class="product-img">'+(p.image?'<img src="'+p.image+'" alt="">':"▦")+'</div><div><h3>'+p.name+'</h3><p>'+([p.brand,p.quantity,p.barcode].filter(Boolean).join(" · "))+(localOnly?" · non trovato nel catalogo pubblico":"")+'</p></div></div><div class="actions"><button class="primary" id="saveBarcodeProduct">'+(linkingProductId?"Abbina a questo prodotto":"Aggiungi al catalogo")+'</button></div></div>';$("#saveBarcodeProduct").addEventListener("click",saveBarcodeProduct);}
function saveBarcodeProduct(){if(!barcodeCandidate)return;let p=linkingProductId?state.products.find(x=>x.id===linkingProductId):state.products.find(x=>x.barcode===barcodeCandidate.barcode);if(!p){p={id:uid("p"),aliases:[],prices:[]};state.products.push(p);}p.barcode=barcodeCandidate.barcode;p.name=barcodeCandidate.name||p.name;p.brand=barcodeCandidate.brand||p.brand||"";p.quantity=barcodeCandidate.quantity||p.quantity||"";p.image=barcodeCandidate.image||p.image||"";$("#barcodeModal").classList.remove("open");linkingProductId=null;save();toast("Prodotto salvato");}
$("#expenseForm").addEventListener("submit",e=>{e.preventDefault();const amount=+$("#expAmount").value;if(!amount)return;state.expenses.push({id:uid("e"),amount,store:$("#expStoreValue").value,category:$("#expCategoryValue").value,note:$("#expNote").value.trim()});e.target.reset();selectChoice("expStoreValue","Eurospin");selectChoice("expCategoryValue","Alimentari");$("#expenseModal").classList.remove("open");save();toast("Spesa registrata");});
$("#shopForm").addEventListener("submit",e=>{e.preventDefault();const name=$("#shopName").value.trim();if(!name)return;state.shopping.push({id:Date.now(),name,store:$("#shopStoreValue").value,day:+$("#shopDayValue").value,price:+$("#shopPrice").value||0,done:false});e.target.reset();selectChoice("shopStoreValue","Eurospin");selectChoice("shopDayValue","1");$("#shopModal").classList.remove("open");save();toast("Aggiunto alla lista");});
$("#pantryForm").addEventListener("submit",e=>{e.preventDefault();const name=$("#pantryName").value.trim();if(!name)return;state.pantry.push({id:Date.now(),name,pct:+$("#pantryLevelValue").value,type:$("#pantryTypeValue").value,icon:$("#pantryIcon").value});e.target.reset();selectChoice("pantryLevelValue","100");selectChoice("pantryTypeValue","normal");$("#pantryModal").classList.remove("open");save();toast("Aggiunto in dispensa");});
function openPantryCamera(){$("#cameraInput").click();}$("#cameraBtn").addEventListener("click",openPantryCamera);$("#homeCamera").addEventListener("click",()=>{switchScreen("pantry");setTimeout(openPantryCamera,160);});$("#cameraInput").addEventListener("change",e=>{const f=e.target.files&&e.target.files[0];if(!f)return;const url=URL.createObjectURL(f);$("#photoBox").innerHTML='<img src="'+url+'" alt="Foto dispensa">';$("#photoBox").style.display="block";toast("Foto dispensa aggiunta");});
$("#copyBtn").addEventListener("click",async()=>{try{await navigator.clipboard.writeText(makeReview());toast("Review copiata");}catch(e){toast("Usa Scarica");}});$("#downloadBtn").addEventListener("click",()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([makeReview()],{type:"text/plain"}));a.download="family-cfo-review.txt";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);});$("#menuRefresh").addEventListener("click",()=>toast("Il menu verrà ottimizzato nella review ChatGPT"));$("#profileBtn").addEventListener("click",()=>toast("Family CFO V3"));
render();
